spring:
  application:
    name: DARAM-server-V2
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${DB_TYPE:mariadb}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:daram}?serverTimezone=KST
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          batch_size: 50
        order_updates: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: caffeine
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "${FRONT_URL}/login/oauth2/code/google"
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            client-name: google
logging:
  level:
    root: error
    org.springframework.security: warn
    org.springframework.web: warn
  file:
    path: /var/logs/daram/application.log
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    enabled-by-default: false
token:
  secret: ${TOKEN_SECRET}
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000
  refresh-token-validity: 604800000
production:
  url: ${PROD_URL}
  front-url: ${FRONT_URL}
server:
  servlet:
    context-path: /api/v2